Traceback (most recent call last):
  File "/home/trinity.conn/.conda/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/trinity.conn/.conda/envs/funannotate/lib/python3.9/site-packages/funannotate/funannotate.py", line 715, in main
    mod = importlib.import_module(
  File "/home/trinity.conn/.conda/envs/funannotate/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/trinity.conn/.conda/envs/funannotate/lib/python3.9/site-packages/funannotate/train.py", line 10, in <module>
    import funannotate.library as lib
  File "/home/trinity.conn/.conda/envs/funannotate/lib/python3.9/site-packages/funannotate/library.py", line 17, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
